# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=128)),
                ('student_last_name', models.CharField(max_length=128)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_booking_status', models.BooleanField()),
                ('is_tutor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor_first_name', models.CharField(max_length=128)),
                ('tutor_last_name', models.CharField(max_length=128)),
                ('tutor_email', models.EmailField(max_length=254, unique=True)),
                ('tutor_booking_status', models.BooleanField()),
                ('is_student', models.BooleanField()),
                ('university_name', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tutor_intro', models.TextField()),
            ],
        ),
    ]
