# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171021_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='available_times',
            new_name='available_time',
        ),
    ]
