# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171021_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='available_time',
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_time',
            field=models.ForeignKey(default='10:30', on_delete=django.db.models.deletion.CASCADE, to='main.Availability'),
            preserve_default=False,
        ),
    ]
