# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171022_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='available_time',
        ),
    ]
