# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tutor_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='weekday',
        ),
    ]
