# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171022_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
    ]
