# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_availability_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default='10:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default='12:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='available_time',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Availability'),
        ),
    ]
