# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='q_student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='q_tutor',
            new_name='tutor',
        ),
    ]
