# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171024_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('tutor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor')),
            ],
        ),
    ]
