# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20171028_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tutorFirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor_last_name',
            new_name='lastName',
        ),
    ]
