# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171028_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='booked_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Availability'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='tutor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor'),
        ),
    ]
